version: '3.5'
services:
  aggregation-service:
    image: ghcr.io/just-be-organisation/better.aggregation-service
    environment:
      - POSTGRES_AGGREGATION_SERVICE_DB=${POSTGRES_AGGREGATION_SERVICE_DB}
      - POSTGRES_AGGREGATION_SERVICE_USER=${POSTGRES_AGGREGATION_SERVICE_USER}
      - POSTGRES_AGGREGATION_SERVICE_PASSWORD=${POSTGRES_AGGREGATION_SERVICE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 8079:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.1"
          memory: "128M"
networks:
  default:
    external:
      name: better

